### ISSUE TITLE
Uninstall the patch

### ISSUE THREAD

**Issue by thebitguru** [thebitguru/play-button-itunes-patch#11]
Hi Farhan,

Install the patches, found out all the remote buttons are disabled. I rerun the patch to undo the changes, but the remote button is still not working. I am running 10.9.4. Any advise?

Created from comment at http://www.thebitguru.com/projects/iTunesPatch

**Comment by thebitguru** [comment]
Closing since I haven't seen a response in a while.

**Comment by jacksonmcclelland** [comment]
Hi, can you help me with uninstalling? Play / pause doesn't seem to be working at all anymore, and I'd like to see if the patch is the cause of this.

**Comment by thebitguru** [comment]
@jacksonmcclelland The GUI app should allow you to uninstall.  Have you tried that?

**Comment by jacksonmcclelland** [comment]
works, thank you!




Jack
