### ISSUE TITLE
You can't use this version of the application with this version of OS X

### ISSUE THREAD

**Issue by codefox421** [thebitguru/play-button-itunes-patch#15]
When trying to launch the GUI patch (0.9 as downloaded [here](http://www.thebitguru.com/projects/iTunesPatch)), I receive the following message:

> **You can't use this version of the application "Play Button iTunes Patch" with this version of OS X.**
> You have OS X 10.9.4. The application requires OS X 10.10 or later.

**Comment by codefox421** [comment]
This version runs on my system. Thanks! :+1:

**Comment by thebitguru** [comment]
Excellent!  Thanks for confirming.  I will go ahead and close this issue.
