### ISSUE TITLE
Version 10.10.1 (Build 14B25) - Unexpected Error

### ISSUE THREAD

**Issue by 360fun** [thebitguru/play-button-itunes-patch#16]
Hi, I get this error:
"Could not codesign the modified binary."

![image](https://cloud.githubusercontent.com/assets/844090/5586553/86da88c2-90d2-11e4-9c2d-8b38e8d28ae2.png)

iTunes still starts if I press the Play/Pause button... :(

**Comment by 360fun** [comment]
ok, found the problem: I just installed OSX and XCode so I had to agree to the licence in order to use Python! ;) would be better find a strategy to avoid this problem or notice the user with an alert message.

---

a part that, this is my log file, I have another error about the updater, just check if is something to fix or is all ok:
02/01/15 10:32:19,000 kernel[0]: hfs: mounted Play Button iTunes Patch on device disk1s2
02/01/15 10:32:19,159 mds[37]: (Volume.Normal:2464) volume:0x7fedda87a200 ********** Bootstrapped Creating a default store:1 SpotLoc:(null) SpotVerLoc:(null) occlude:0 /Volumes/Play Button iTunes Patch
02/01/15 10:32:35,122 Play Button iTunes Patch[14696]: Unknown class 'SUUpdater', using 'NSObject' instead. Encountered in Interface Builder file at path /Applications/Play Button iTunes Patch.app/Contents/Resources/Base.lproj/MainMenu.nib.
02/01/15 10:33:03,321 Play Button iTunes Patch[14696]: Problem running task: Could not codesign the modified binary.

anyway, nice work!!! ;)

**Comment by 360fun** [comment]
wait! actually the patch is not working, the GUI tells me that everything is fine but iTunes still lunches with my earpods! instead the command line patch works perfectly...no idea why.

**Comment by thebitguru** [comment]
The SUUpdate error is resolved in the latest build that I uploaded a few days ago.  It shouldn't effect this problem though.

I wonder if this is because the rcd process isn't restarted by the GUI.  I will add that to the next build and have another user try it out.

I will close this issue once I get that change implemented and uploaded.  Thanks for your help!

**Comment by 360fun** [comment]
no problem :) let me know when it's ready!

**Comment by thebitguru** [comment]
I just published an update that checks for the command line tools, and correctly kills and restarts the `rcd` process.  The latest version also has plenty of logging built in so hopefully issues would be more obvious.

Please download 1.0 from http://www.thebitguru.com/projects/iTunesPatch.

I am going to close this for now.  Please create a new issue if you experience any other problems.  Thanks!
