### ISSUE TITLE
GUI app, after patching, system needs to be restarted in order for the patch to work

### ISSUE THREAD

**Issue by neoyoli** [thebitguru/play-button-itunes-patch#17]
so it should be stated in the instructions, in order to avoid confusion.

**Comment by thebitguru** [comment]
I think forcing the `rcd` process to restart will achieve the same result.  This is a step that I need to add.  I will keep this ticket open until I have gotten around to that.  Thanks for reporting this, @neoyoli.

**Comment by runofthemill** [comment]
Was about to post the same issue - works perfect after restart, but agree a note in app instructions would have prevented confusion. Maybe addressable as a quicker fix than forcing `rcd` restart? Cheers for the app though!

**Comment by thebitguru** [comment]
I just published an update that correctly kills and restarts the `rcd` process.  This means that the user doesn't have to restart the system.  I still added a message recommending to restart in case if the process restart didn't work for some reason.  Please download 1.0 from http://www.thebitguru.com/projects/iTunesPatch.

Closing this issue.  Thanks again for creating reporting it!

**Comment by neoyoli** [comment]
Thanks, I downloaded it!
