### ISSUE TITLE
Could not codesign the modified binary.

### ISSUE THREAD

**Issue by dirichlet222** [thebitguru/play-button-itunes-patch#18]
I already had Xcode and the command line tools installed

User name has been substituted from privacy in the log:

2015/03/26 19:03:07:971 | INFO | AppDelegate:65 - --------------- New session - Version 1.0 ---------------
2015/03/26 19:03:07:977 | INFO | AppDelegate:66 - Log file directory: /Users/macuser/Library/Logs/Play Button iTunes Patch
2015/03/26 19:03:07:980 | INFO | AppDelegate:78 - OS Version: Version 10.10.2 (Build 14C2055)
2015/03/26 19:03:07:980 | DEBUG | Patcher:21 - Initializing.
2015/03/26 19:03:07:980 | DEBUG | Patcher:22 - RCD_PATH: /System/Library/CoreServices/rcd.app/Contents/MacOS/
2015/03/26 19:03:07:981 | DEBUG | Patcher:31 - Find command data: <74656c6c 20617070 6c696361 74696f6e 20696420 22636f6d 2e617070 6c652e69 54756e65 73222074 6f206c61 756e6368>
2015/03/26 19:03:07:981 | DEBUG | Patcher:32 - Replace command data: <2d2d6c6c 20617070 6c696361 74696f6e 20696420 22636f6d 2e617070 6c652e69 54756e65 73222074 6f206c61 756e6368>
2015/03/26 19:03:07:981 | DEBUG | Patcher:41 - Finished initializing.
2015/03/26 19:03:07:982 | INFO | AppDelegate:173 - Refreshing view...
2015/03/26 19:03:07:982 | DEBUG | Patcher:78 - Loading files and determing file statuses...
2015/03/26 19:03:07:985 | INFO | Patcher:142 - File: rcd, Patched: 0, MD5: 561cbe17e21a78f898c25f05d61f9f88, Date modified: 2014-11-07 03:12:47 +0000, Comments: Unpatched.
2015/03/26 19:03:07:992 | DEBUG | Patcher:69 - _areCommandLineToolsInstalled = 0
2015/03/26 19:03:07:992 | WARNING | Patcher:71 - Command line tools NOT installed.
2015/03/26 19:03:07:992 | INFO | AppDelegate:180 - File is unpatched.
2015/03/26 19:03:07:992 | INFO | AppDelegate:189 - No backups found.
2015/03/26 19:03:07:993 | VERBOSE | AppDelegate:252 - Finished refreshing view.
2015/03/26 19:03:34:945 | INFO | AppDelegate:362 - Use requested to patch...
2015/03/26 19:03:34:949 | INFO | AppDelegate:367 - Command line tools are not installed, confirming to proceed with the install.
2015/03/26 19:04:10:608 | INFO | AppDelegate:372 - Use decided not to install. Aborting patch.
2015/03/26 19:24:27:080 | INFO | AppDelegate:92 - =============== applicationWillTerminate ===============
2015/03/26 20:47:02:307 | INFO | AppDelegate:65 - --------------- New session - Version 1.0 ---------------
2015/03/26 20:47:02:312 | INFO | AppDelegate:66 - Log file directory: /Users/macuser/Library/Logs/Play Button iTunes Patch
2015/03/26 20:47:02:313 | INFO | AppDelegate:78 - OS Version: Version 10.10.2 (Build 14C2055)
2015/03/26 20:47:02:313 | DEBUG | Patcher:21 - Initializing.
2015/03/26 20:47:02:314 | DEBUG | Patcher:22 - RCD_PATH: /System/Library/CoreServices/rcd.app/Contents/MacOS/
2015/03/26 20:47:02:314 | DEBUG | Patcher:31 - Find command data: <74656c6c 20617070 6c696361 74696f6e 20696420 22636f6d 2e617070 6c652e69 54756e65 73222074 6f206c61 756e6368>
2015/03/26 20:47:02:314 | DEBUG | Patcher:32 - Replace command data: <2d2d6c6c 20617070 6c696361 74696f6e 20696420 22636f6d 2e617070 6c652e69 54756e65 73222074 6f206c61 756e6368>
2015/03/26 20:47:02:314 | DEBUG | Patcher:41 - Finished initializing.
2015/03/26 20:47:02:316 | INFO | AppDelegate:173 - Refreshing view...
2015/03/26 20:47:02:317 | DEBUG | Patcher:78 - Loading files and determing file statuses...
2015/03/26 20:47:02:320 | INFO | Patcher:142 - File: rcd, Patched: 0, MD5: 561cbe17e21a78f898c25f05d61f9f88, Date modified: 2014-11-07 03:12:47 +0000, Comments: Unpatched.
2015/03/26 20:47:02:331 | DEBUG | Patcher:69 - _areCommandLineToolsInstalled = 1
2015/03/26 20:47:02:332 | INFO | Patcher:73 - Command line tools found.
2015/03/26 20:47:02:332 | INFO | AppDelegate:180 - File is unpatched.
2015/03/26 20:47:02:332 | INFO | AppDelegate:189 - No backups found.
2015/03/26 20:47:02:333 | VERBOSE | AppDelegate:252 - Finished refreshing view.
2015/03/26 20:47:08:346 | INFO | AppDelegate:362 - Use requested to patch...
2015/03/26 20:47:08:349 | INFO | AppDelegate:380 - Xcode command line tools are installed.
2015/03/26 20:47:15:647 | INFO | AppDelegate:393 - Requesting patch...
2015/03/26 20:47:15:647 | INFO | Patcher:161 - Patching rcd...
2015/03/26 20:47:15:647 | INFO | Patcher:176 - Replaced instance #1 at 30754:48
2015/03/26 20:47:15:647 | INFO | Patcher:171 - No more instances.
2015/03/26 20:47:15:648 | INFO | Patcher:184 - Replaced 1 total instances
2015/03/26 20:47:19:689 | INFO | Patcher:204 - Creating backup file /System/Library/CoreServices/rcd.app/Contents/MacOS//rcd_backup_1.0_20150326_20_47.19 before overwriting rcd.
2015/03/26 20:47:19:689 | DEBUG | Patcher:280 - writeDataToProtectedFile: /System/Library/CoreServices/rcd.app/Contents/MacOS//rcd_backup_1.0_20150326_20_47.19
2015/03/26 20:47:19:703 | INFO | Patcher:209 - Writing the updated bytes to original file (/System/Library/CoreServices/rcd.app/Contents/MacOS//rcd).
2015/03/26 20:47:19:703 | DEBUG | Patcher:280 - writeDataToProtectedFile: /System/Library/CoreServices/rcd.app/Contents/MacOS//rcd
2015/03/26 20:47:19:712 | INFO | Patcher:214 - Signing file.
2015/03/26 20:47:22:910 | ERROR | Patcher:334 - codesign task returned false!
2015/03/26 20:47:22:910 | ERROR | AppDelegate:397 - Problem patching file: Could not codesign the modified binary.
2015/03/26 20:47:26:321 | INFO | AppDelegate:173 - Refreshing view...
2015/03/26 20:47:26:321 | DEBUG | Patcher:78 - Loading files and determing file statuses...
2015/03/26 20:47:26:322 | INFO | Patcher:142 - File: rcd, Patched: 1, MD5: 4d46a35dbf40413861a71bc0291c7f50, Date modified: 2015-03-26 19:47:19 +0000, Comments: Patched.
2015/03/26 20:47:26:323 | INFO | Patcher:142 - File: rcd_backup_1.0_20150326_20_47.19, Patched: 0, MD5: 561cbe17e21a78f898c25f05d61f9f88, Date modified: 2015-03-26 19:47:19 +0000, Comments: Backup file. Unpatched.
2015/03/26 20:47:26:326 | DEBUG | Patcher:69 - _areCommandLineToolsInstalled = 1
2015/03/26 20:47:26:327 | INFO | Patcher:73 - Command line tools found.
2015/03/26 20:47:26:327 | INFO | AppDelegate:177 - File is already patched.
2015/03/26 20:47:26:327 | INFO | AppDelegate:185 - Backups found, enabling restore button.
2015/03/26 20:47:26:327 | VERBOSE | AppDelegate:252 - Finished refreshing view.
2015/03/26 20:47:52:732 | INFO | AppDelegate:256 - Restore from backup clicked...
2015/03/26 20:47:52:732 | INFO | AppDelegate:328 - There is only one backup file: rcd_backup_1.0_20150326_20_47.19
2015/03/26 20:47:52:732 | INFO | AppDelegate:333 - Requesting restore from patcher.
2015/03/26 20:47:52:732 | INFO | Patcher:229 - Kicking off restore from backup file rcd_backup_1.0_20150326_20_47.19
2015/03/26 20:47:55:832 | INFO | Patcher:242 - Killing existing rcd processes...
2015/03/26 20:47:55:832 | INFO | Patcher:303 - Killing all rcd.
2015/03/26 20:47:58:625 | INFO | Patcher:311 - killall returned 'No matching porcesses were found'
2015/03/26 20:47:58:625 | INFO | Patcher:318 - Restarting rcd process as current user.
2015/03/26 20:47:58:630 | INFO | Patcher:245 - Restore complete.
2015/03/26 20:47:58:630 | INFO | AppDelegate:173 - Refreshing view...
2015/03/26 20:47:58:630 | DEBUG | Patcher:78 - Loading files and determing file statuses...
2015/03/26 20:47:58:631 | INFO | Patcher:142 - File: rcd, Patched: 0, MD5: 561cbe17e21a78f898c25f05d61f9f88, Date modified: 2015-03-26 19:47:19 +0000, Comments: Unpatched.
2015/03/26 20:47:58:635 | DEBUG | Patcher:69 - _areCommandLineToolsInstalled = 1
2015/03/26 20:47:58:635 | INFO | Patcher:73 - Command line tools found.
2015/03/26 20:47:58:636 | INFO | AppDelegate:180 - File is unpatched.
2015/03/26 20:47:58:636 | INFO | AppDelegate:189 - No backups found.
2015/03/26 20:47:58:636 | VERBOSE | AppDelegate:252 - Finished refreshing view.
2015/03/26 20:47:58:636 | INFO | AppDelegate:173 - Refreshing view...
2015/03/26 20:47:58:636 | DEBUG | Patcher:78 - Loading files and determing file statuses...
2015/03/26 20:47:58:637 | INFO | Patcher:142 - File: rcd, Patched: 0, MD5: 561cbe17e21a78f898c25f05d61f9f88, Date modified: 2015-03-26 19:47:19 +0000, Comments: Unpatched.
2015/03/26 20:47:58:644 | DEBUG | Patcher:69 - _areCommandLineToolsInstalled = 1
2015/03/26 20:47:58:644 | INFO | Patcher:73 - Command line tools found.
2015/03/26 20:47:58:644 | INFO | AppDelegate:180 - File is unpatched.
2015/03/26 20:47:58:644 | INFO | AppDelegate:189 - No backups found.
2015/03/26 20:47:58:644 | VERBOSE | AppDelegate:252 - Finished refreshing view.
2015/03/26 20:48:10:943 | INFO | AppDelegate:92 - =============== applicationWillTerminate ===============
2015/03/26 21:04:53:208 | INFO | AppDelegate:65 - --------------- New session - Version 1.0 ---------------
2015/03/26 21:04:53:212 | INFO | AppDelegate:66 - Log file directory: /Users/macuser/Library/Logs/Play Button iTunes Patch
2015/03/26 21:04:53:213 | INFO | AppDelegate:78 - OS Version: Version 10.10.2 (Build 14C2513)
2015/03/26 21:04:53:213 | DEBUG | Patcher:21 - Initializing.
2015/03/26 21:04:53:213 | DEBUG | Patcher:22 - RCD_PATH: /System/Library/CoreServices/rcd.app/Contents/MacOS/
2015/03/26 21:04:53:213 | DEBUG | Patcher:31 - Find command data: <74656c6c 20617070 6c696361 74696f6e 20696420 22636f6d 2e617070 6c652e69 54756e65 73222074 6f206c61 756e6368>
2015/03/26 21:04:53:214 | DEBUG | Patcher:32 - Replace command data: <2d2d6c6c 20617070 6c696361 74696f6e 20696420 22636f6d 2e617070 6c652e69 54756e65 73222074 6f206c61 756e6368>
2015/03/26 21:04:53:214 | DEBUG | Patcher:41 - Finished initializing.
2015/03/26 21:04:53:214 | INFO | AppDelegate:173 - Refreshing view...
2015/03/26 21:04:53:214 | DEBUG | Patcher:78 - Loading files and determing file statuses...
2015/03/26 21:04:53:216 | INFO | Patcher:142 - File: rcd, Patched: 0, MD5: 561cbe17e21a78f898c25f05d61f9f88, Date modified: 2015-03-26 19:47:19 +0000, Comments: Unpatched.
2015/03/26 21:04:53:226 | DEBUG | Patcher:69 - _areCommandLineToolsInstalled = 1
2015/03/26 21:04:53:226 | INFO | Patcher:73 - Command line tools found.
2015/03/26 21:04:53:227 | INFO | AppDelegate:180 - File is unpatched.
2015/03/26 21:04:53:227 | INFO | AppDelegate:189 - No backups found.
2015/03/26 21:04:53:228 | VERBOSE | AppDelegate:252 - Finished refreshing view.
2015/03/26 21:04:57:686 | INFO | AppDelegate:362 - Use requested to patch...
2015/03/26 21:04:57:693 | INFO | AppDelegate:380 - Xcode command line tools are installed.
2015/03/26 21:04:59:946 | INFO | AppDelegate:393 - Requesting patch...
2015/03/26 21:04:59:947 | INFO | Patcher:161 - Patching rcd...
2015/03/26 21:04:59:947 | INFO | Patcher:176 - Replaced instance #1 at 30754:48
2015/03/26 21:04:59:947 | INFO | Patcher:171 - No more instances.
2015/03/26 21:04:59:947 | INFO | Patcher:184 - Replaced 1 total instances
2015/03/26 21:05:03:450 | INFO | Patcher:204 - Creating backup file /System/Library/CoreServices/rcd.app/Contents/MacOS//rcd_backup_1.0_20150326_21_05.03 before overwriting rcd.
2015/03/26 21:05:03:450 | DEBUG | Patcher:280 - writeDataToProtectedFile: /System/Library/CoreServices/rcd.app/Contents/MacOS//rcd_backup_1.0_20150326_21_05.03
2015/03/26 21:05:03:463 | INFO | Patcher:209 - Writing the updated bytes to original file (/System/Library/CoreServices/rcd.app/Contents/MacOS//rcd).
2015/03/26 21:05:03:463 | DEBUG | Patcher:280 - writeDataToProtectedFile: /System/Library/CoreServices/rcd.app/Contents/MacOS//rcd
2015/03/26 21:05:03:470 | INFO | Patcher:214 - Signing file.
2015/03/26 21:05:10:817 | ERROR | Patcher:334 - codesign task returned false!
2015/03/26 21:05:10:817 | ERROR | AppDelegate:397 - Problem patching file: Could not codesign the modified binary.
2015/03/26 21:05:14:461 | INFO | AppDelegate:173 - Refreshing view...
2015/03/26 21:05:14:461 | DEBUG | Patcher:78 - Loading files and determing file statuses...
2015/03/26 21:05:14:462 | INFO | Patcher:142 - File: rcd, Patched: 1, MD5: 4d46a35dbf40413861a71bc0291c7f50, Date modified: 2015-03-26 20:05:03 +0000, Comments: Patched.
2015/03/26 21:05:14:462 | INFO | Patcher:142 - File: rcd_backup_1.0_20150326_21_05.03, Patched: 0, MD5: 561cbe17e21a78f898c25f05d61f9f88, Date modified: 2015-03-26 20:05:03 +0000, Comments: Backup file. Unpatched.
2015/03/26 21:05:14:466 | DEBUG | Patcher:69 - _areCommandLineToolsInstalled = 1
2015/03/26 21:05:14:467 | INFO | Patcher:73 - Command line tools found.
2015/03/26 21:05:14:467 | INFO | AppDelegate:177 - File is already patched.
2015/03/26 21:05:14:467 | INFO | AppDelegate:185 - Backups found, enabling restore button.
2015/03/26 21:05:14:467 | VERBOSE | AppDelegate:252 - Finished refreshing view.

**Comment by dirichlet222** [comment]
Never mind, now it works, the OS needed a reboot after installing Xcode+CLT. Maybe add a warning for that?

**Comment by jmartinezmd** [comment]
I have the same error here, Already had Xcode and CTL installed.... I tried restarting but still the same :(
