### ISSUE TITLE
Yosemite 10.10.3

### ISSUE THREAD

**Issue by Cam1337** [thebitguru/play-button-itunes-patch#19]
I saw that you confirmed the beta2 of Yosemite works, but I am not experiencing functionality in 10.10.3. I am not experiencing crashes or any logs in console.app but iTunes is still opening after successfully applying the patch. I can submit a video if you would like proof, and any more files that would be relevant. 

Thank you!

Best,
Cameron

**Comment by Cam1337** [comment]
I'm glad I resolved this 10 seconds after posting and 3 hours after starting. The issue seems to be that the current github app is version 0.9 and the app on your website is 1.0. I would suggest updating the app here for those of us that chose to download with a git clone command instead of through your official website DMG.

Thank you!

**Comment by thebitguru** [comment]
Hi @Cam1337,

Sorry, I am not sure what you mean.  I confirmed that I don't have any releases on github.  Did you manually compile?
