### ISSUE TITLE
Patch does not work with 10.10.3 Build 14D136

### ISSUE THREAD

**Issue by psarossy** [thebitguru/play-button-itunes-patch#21]
hey,

I did the patch, it created the back up and shows that RCD is parched, itunes still starts.

Cheers,
Peter

**Comment by thebitguru** [comment]
This might be a little late, but can you run the app and share the log?

**Comment by kevincoleman** [comment]
If you run old-cli/Patch.command, it works correctly. 10.10.3; 14D136, iTunes v12.1.2.27.

Verified that the package does not work, symptoms as @psarossy mentioned.

Here’s my log from XCode (not sure if it’s what you’re looking for...): https://gist.github.com/kevincoleman/7c382aad487beed7a383

**Comment by thebitguru** [comment]
I believe this has been fixed with the most recent dmg.
