### ISSUE TITLE
Chrome global media keys don't work with patch 

### ISSUE THREAD

**Issue by NinoFloris** [thebitguru/play-button-itunes-patch#23]
Hi guys, 

Chrome global media keys die when the rcd is patched.

Tested on OSX Yosemite 10.10.4 with Chrome 44.

**Comment by thebitguru** [comment]
Hi @NinoFloris, can you please let me know if this is still an issue?  I am surprised that this would interfere.  I am going to close the issue for now.  Can you please reopen with instructions on how I can reproduce it?  Thanks!
