### ISSUE TITLE
After restoring from backup, seeing a 'rcd quit unexpectedly.' dialog every 10 seconds

### ISSUE THREAD

**Issue by jonnynezbo** [thebitguru/play-button-itunes-patch#24]
The dialog begins appearing repeatedly after I press the play button after restoring from backup.

Here's a screenshot of the dialog:

https://dl.dropboxusercontent.com/spa/w9y331nq8d0g5zi/sxak2-pn.png

And here's the report from the dialog:

Process:               rcd [650]
Path:                  /System/Library/CoreServices/rcd.app/Contents/MacOS/rcd
Identifier:            rcd
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           rcd [650]
User ID:               501

Date/Time:             2015-08-07 11:58:35.829 -0400
OS Version:            Mac OS X 10.10.4 (14E46)
Report Version:        11
Anonymous UUID:        7E137903-33E8-DC8C-14F9-4D763D80E9E9

Time Awake Since Boot: 110 seconds

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000

kernel messages:

VM Regions Near 0x7fff7a22b0a0 (cr2):
    __LINKEDIT             00007fff61768000-00007fff6177c000 [   80K] r--/rwx SM=COW  /usr/lib/dyld
--> Submap                 00007fff70000000-00007fff80000000 [256.0M] r--/rwx SM=PRV  process-only VM submap
    unused shlib __DATA    00007fff79d63000-00007fff7c363000 [ 38.0M] rw-/rw- SM=COW  system shared lib __DATA not used by this process

Thread 0 Crashed:
0   dyld                          	0x00007fff616f9000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x000000000000000d  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007fff56264d28
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff616f9000  rfl: 0x0000000000000201  cr2: 0x00007fff7a22b0a0
  
Logical CPU:     0
Error Code:      0x020000f4
Trap Number:     133

Binary Images:
    0x7fff616f8000 -     0x7fff6172e837  dyld (???) <72A99D0F-0B56-3938-ABC5-67A0F33757C4> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 688
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=300K resident=300K(100%) swapped_out_or_unallocated=0K(0%)
Writable regions: Total=8416K written=0K(0%) resident=12K(0%) swapped_out=0K(0%) unallocated=8404K(100%)
 
REGION TYPE                      VIRTUAL
===========                      =======
STACK GUARD                        56.0M
Stack                              8192K
VM_ALLOCATE                           8K
VM_ALLOCATE (reserved)                4K        reserved VM address space (unallocated)
__DATA                              228K
__LINKEDIT                           80K
__TEXT                              220K
mapped file                          72K
shared memory                         4K
===========                      =======
TOTAL                              64.6M
TOTAL, minus reserved VM space     64.6M

**Comment by jonnynezbo** [comment]
I am trying to remove the patch because my play/pause button doesn't work in iTunes for some reason. I wanted to rule out the patch as the cause.

**Comment by jonnynezbo** [comment]
It's worth noting that I was using an older version of the patch (pre Mac app). I tried restoring using that first, and the problem happened then. So, I installed the app in hopes that it would clear the issue up - but it's still happening. I'm stuck with the patch installed for now. I'm using Apple Music now, so I actually prefer to have the play button launch iTunes now.

**Comment by jonnynezbo** [comment]
For now, I'm just running the patch and hoping for a fix. It's not annoying enough to to a fresh install of OS X, but it is frustrating none the less.

I appreciate your efforts in developing this patch that worked well for so long. I know you're doing it for free, and it can be frustrating for support an app that doesn't make you any money!

**Comment by thebitguru** [comment]
Hi @jonnynezbo,

Yeah, you should not have to do a fresh install to fix this.  Can you run the GUI patch and share the log?  Most likely you are missing the OS X command line tools where the binary gets patched, but cannot be signed.

**Comment by jonnynezbo** [comment]
Thanks for the reply @thebitguru. I could not find the log when patching with the GUI app. All I see is this:

https://dl.dropboxusercontent.com/spa/w9y331nq8d0g5zi/64a48i6d.png

**Comment by thebitguru** [comment]
It's in the application menu as shown below.

![image](https://cloud.githubusercontent.com/assets/163550/9145898/bbecbd6c-3d1d-11e5-9362-14dd52dfe52c.png)

Did using the GUI version fix the issue?  If not then can you share the log file with me?  I am on 10.10.4 so I am surprised that this didn't work for you.

If you would like to back out the patch... right click on the file that says "Unpatched" and choose Show in Finder.  Once in the correct folder in Finder, delete the `rcd` file, rename the backup that you selected to `rcd` and restart.

![image](https://cloud.githubusercontent.com/assets/163550/9145969/763e6e68-3d1e-11e5-9d33-3045c9ff0a89.png)

**Comment by jonnynezbo** [comment]
Sorry it took me so long to respond. Here is the log from when I patch:

    2015/08/11 11:15:14:769 | INFO | AppDelegate:65 - --------------- New session - Version 1.0 ---------------
    2015/08/11 11:15:14:773 | INFO | AppDelegate:66 - Log file directory: /Users/jonathan/Library/Logs/Play Button iTunes Patch
    2015/08/11 11:15:14:773 | INFO | AppDelegate:78 - OS Version: Version 10.10.4 (Build 14E46)
    2015/08/11 11:15:14:773 | DEBUG | Patcher:21 - Initializing.
    2015/08/11 11:15:14:774 | DEBUG | Patcher:22 - RCD_PATH: /System/Library/CoreServices/rcd.app/Contents/MacOS/
    2015/08/11 11:15:14:774 | DEBUG | Patcher:31 - Find command data: <74656c6c 20617070 6c696361 74696f6e 20696420 22636f6d 2e617070 6c652e69 54756e65 73222074 6f206c61 756e6368>
    2015/08/11 11:15:14:774 | DEBUG | Patcher:32 - Replace command data: <2d2d6c6c 20617070 6c696361 74696f6e 20696420 22636f6d 2e617070 6c652e69 54756e65 73222074 6f206c61 756e6368>
    2015/08/11 11:15:14:774 | DEBUG | Patcher:41 - Finished initializing.
    2015/08/11 11:15:14:774 | INFO | AppDelegate:173 - Refreshing view...
    2015/08/11 11:15:14:774 | DEBUG | Patcher:78 - Loading files and determing file statuses...
    2015/08/11 11:15:14:777 | INFO | Patcher:142 - File: rcd, Patched: 1, MD5: 06851d24f50008a9a8170b20c9d0c413, Date modified: 2015-08-07 20:37:03 +0000, Comments: Patched.
    2015/08/11 11:15:14:778 | INFO | Patcher:142 - File: rcd_backup_1.0_20150807_16_34.50, Patched: 0, MD5: 9b59dabcaad75b75aa79b1ef7cce936f, Date modified: 2015-08-07 20:34:50 +0000, Comments: Backup file. Unpatched.
    2015/08/11 11:15:14:786 | DEBUG | Patcher:69 - _areCommandLineToolsInstalled = 1
    2015/08/11 11:15:14:786 | INFO | Patcher:73 - Command line tools found.
    2015/08/11 11:15:14:786 | INFO | AppDelegate:177 - File is already patched.
    2015/08/11 11:15:14:786 | INFO | AppDelegate:185 - Backups found, enabling restore button.
    2015/08/11 11:15:14:787 | VERBOSE | AppDelegate:252 - Finished refreshing view.
    2015/08/11 11:15:21:558 | INFO | AppDelegate:256 - Restore from backup clicked...
    2015/08/11 11:15:21:558 | INFO | AppDelegate:328 - There is only one backup file: rcd_backup_1.0_20150807_16_34.50
    2015/08/11 11:15:21:558 | INFO | AppDelegate:333 - Requesting restore from patcher.
    2015/08/11 11:15:21:559 | INFO | Patcher:229 - Kicking off restore from backup file rcd_backup_1.0_20150807_16_34.50
    2015/08/11 11:15:24:321 | INFO | Patcher:242 - Killing existing rcd processes...
    2015/08/11 11:15:24:321 | INFO | Patcher:303 - Killing all rcd.
    2015/08/11 11:15:26:070 | INFO | Patcher:311 - killall returned 'No matching porcesses were found'
    2015/08/11 11:15:26:070 | INFO | Patcher:318 - Restarting rcd process as current user.
    2015/08/11 11:15:26:079 | INFO | Patcher:245 - Restore complete.
    2015/08/11 11:15:26:079 | INFO | AppDelegate:173 - Refreshing view...
    2015/08/11 11:15:26:079 | DEBUG | Patcher:78 - Loading files and determing file statuses...
    2015/08/11 11:15:26:080 | INFO | Patcher:142 - File: rcd, Patched: 0, MD5: 9b59dabcaad75b75aa79b1ef7cce936f, Date modified: 2015-08-07 20:34:50 +0000, Comments: Unpatched.
    2015/08/11 11:15:26:085 | DEBUG | Patcher:69 - _areCommandLineToolsInstalled = 1
    2015/08/11 11:15:26:085 | INFO | Patcher:73 - Command line tools found.
    2015/08/11 11:15:26:086 | INFO | AppDelegate:180 - File is unpatched.
    2015/08/11 11:15:26:086 | INFO | AppDelegate:189 - No backups found.
    2015/08/11 11:15:26:086 | VERBOSE | AppDelegate:252 - Finished refreshing view.
    2015/08/11 11:15:26:086 | INFO | AppDelegate:173 - Refreshing view...
    2015/08/11 11:15:26:086 | DEBUG | Patcher:78 - Loading files and determing file statuses...
    2015/08/11 11:15:26:087 | INFO | Patcher:142 - File: rcd, Patched: 0, MD5: 9b59dabcaad75b75aa79b1ef7cce936f, Date modified: 2015-08-07 20:34:50 +0000, Comments: Unpatched.
    2015/08/11 11:15:26:091 | DEBUG | Patcher:69 - _areCommandLineToolsInstalled = 1
    2015/08/11 11:15:26:091 | INFO | Patcher:73 - Command line tools found.
    2015/08/11 11:15:26:092 | INFO | AppDelegate:180 - File is unpatched.
    2015/08/11 11:15:26:092 | INFO | AppDelegate:189 - No backups found.
    2015/08/11 11:15:26:092 | VERBOSE | AppDelegate:252 - Finished refreshing view.
    2015/08/11 11:16:19:941 | INFO | AppDelegate:362 - Use requested to patch...
    2015/08/11 11:16:19:943 | INFO | AppDelegate:380 - Xcode command line tools are installed.
    2015/08/11 11:16:21:972 | INFO | AppDelegate:393 - Requesting patch...
    2015/08/11 11:16:21:972 | INFO | Patcher:161 - Patching rcd...
    2015/08/11 11:16:21:972 | INFO | Patcher:176 - Replaced instance #1 at 30754:48
    2015/08/11 11:16:21:972 | INFO | Patcher:171 - No more instances.
    2015/08/11 11:16:21:973 | INFO | Patcher:184 - Replaced 1 total instances
    2015/08/11 11:16:23:946 | INFO | Patcher:204 - Creating backup file /System/Library/CoreServices/rcd.app/Contents/MacOS//rcd_backup_1.0_20150811_11_16.23 before overwriting rcd.
    2015/08/11 11:16:23:946 | DEBUG | Patcher:280 - writeDataToProtectedFile: /System/Library/CoreServices/rcd.app/Contents/MacOS//rcd_backup_1.0_20150811_11_16.23
    2015/08/11 11:16:23:957 | INFO | Patcher:209 - Writing the updated bytes to original file (/System/Library/CoreServices/rcd.app/Contents/MacOS//rcd).
    2015/08/11 11:16:23:957 | DEBUG | Patcher:280 - writeDataToProtectedFile: /System/Library/CoreServices/rcd.app/Contents/MacOS//rcd
    2015/08/11 11:16:23:964 | INFO | Patcher:214 - Signing file.
    2015/08/11 11:16:26:729 | INFO | Patcher:218 - Killing existing rcd processes...
    2015/08/11 11:16:26:729 | INFO | Patcher:303 - Killing all rcd.
    2015/08/11 11:16:28:454 | INFO | Patcher:311 - killall returned 'No matching porcesses were found'
    2015/08/11 11:16:28:455 | INFO | Patcher:318 - Restarting rcd process as current user.
    2015/08/11 11:16:28:456 | INFO | AppDelegate:173 - Refreshing view...
    2015/08/11 11:16:28:456 | DEBUG | Patcher:78 - Loading files and determing file statuses...
    2015/08/11 11:16:28:457 | INFO | Patcher:142 - File: rcd, Patched: 1, MD5: 76dff1668c61d5b4a6ea66f17f1f79a1, Date modified: 2015-08-11 15:16:26 +0000, Comments: Patched.
    2015/08/11 11:16:28:458 | INFO | Patcher:142 - File: rcd_backup_1.0_20150811_11_16.23, Patched: 0, MD5: 9b59dabcaad75b75aa79b1ef7cce936f, Date modified: 2015-08-11 15:16:23 +0000, Comments: Backup file. Unpatched.
    2015/08/11 11:16:28:463 | DEBUG | Patcher:69 - _areCommandLineToolsInstalled = 1
    2015/08/11 11:16:28:463 | INFO | Patcher:73 - Command line tools found.
    2015/08/11 11:16:28:463 | INFO | AppDelegate:177 - File is already patched.
    2015/08/11 11:16:28:464 | INFO | AppDelegate:185 - Backups found, enabling restore button.
    2015/08/11 11:16:28:465 | VERBOSE | AppDelegate:252 - Finished refreshing view.
    2015/08/11 11:16:37:992 | DEBUG | AppDelegate:356 - Showing the log file directory in Finder: /Users/jonathan/Library/Logs/Play Button iTunes Patch

**Comment by jonnynezbo** [comment]
Unfortunately the GUI app did not fix the issue. I downloaded it in hopes that it would. The problem happened when I backed out the patch that I applied over 6 months ago.

**Comment by jonnynezbo** [comment]
To be clear, I'm seeing the error screen continuously **after** I back out the patch. When the patch is installed, then I don't see the error screen and it appears to work as intended. If there is a way to re-install the original rcd for 10.10.4, maybe that would fix the issue. Could there be interference with another app? Like Boom 2 for Mac?

**Comment by thebitguru** [comment]
Hi @jonnynezbo, sorry, I have been quite busy.  Were you able to get this resolved?

**Comment by jonnynezbo** [comment]
I was never able to fix the issue. It worked well for a long time, but at some point it starting showing the 'rcd quit unexpectedly' dialog every 10 seconds. I did a fresh install of OS X awhile back, and haven't installed the utility since then.

**Comment by jonnynezbo** [comment]
BTW, thanks for the work you put into it - and giving it away for free.

**Comment by thebitguru** [comment]
Np :)  I have been on a clean install, and just applied the patch yesterday by temporarily disabling SIP.  See the instructions on the site if you are still looking for this.
