### ISSUE TITLE
Path does not work with Samsung Level Over

### ISSUE THREAD

**Issue by akszydelko** [thebitguru/play-button-itunes-patch#27]
Hi,

I have pathed my mac and also restarted the system (it showed me success message), but it is not working iTunes is still opening. I am using the Samsung Level Over headphones and mavericks 10.9.5.

I can help with debugging if anyone will tell me how ;)

**Comment by thebitguru** [comment]
Hi @akszydelko, do you know if it required you to install any additional software?

**Comment by thebitguru** [comment]
Sorry, unfortunately, I likely won't get much time to work on the bluetooth related functionality.  I have created #29 to track this in a single issue.  I am looking for someone who can take on this work.  Thanks!
