### ISSUE TITLE
rcd crashing after applying patch

### ISSUE THREAD

**Issue by ashumeet** [thebitguru/play-button-itunes-patch#30]
I disabled the file system protection and applied the patch. But rcd starts crashing right after the patch. And I have to restore the rcd from backup to make it work. :(

Please help. After hours and hours spend on google looking for a solution I found this.

**Comment by thebitguru** [comment]
Can you share more info on what you see when it crashes?

**Comment by ashumeet** [comment]
I made it work. I applied the patch before disabling SIP. Obviously it failed. But even after disabling SIP it kept on failing (I even tried to restore it from the backup the GUI makes). I had to go in my timeMachine system backup and copy rcd.app to the location, and applied the patch and it worked.

Moral of story.. DON'T try to apply patch before disabling SIP on OS X El Capitan.

**Comment by thebitguru** [comment]
Hmm... I am surprised that this would have mattered.  If SIP is enabled then the utility wouldn't have been successful at patching the file so when you applied it again after disabling SIP then it should have just worked.

I am glad that you figured it out!
