### ISSUE TITLE
Doesn't work anymore on iTunes 12.5.1

### ISSUE THREAD

**Issue by AnthoPakPak** [thebitguru/play-button-itunes-patch#34]
Everything was working well until I updated iTunes to 12.5.1. 
It doesn't seems to work anymore (even with patching again).
Even if the patching work is successful, the Play key is still opening iTunes.

**Comment by AnthoPakPak** [comment]
Works after rebooting, sorry !

**Comment by thebitguru** [comment]
Glad to hear.  Thanks!
