### ISSUE TITLE
App Crashes and Disappears After I Enter Password

### ISSUE THREAD

**Issue by OliverPearmain** [thebitguru/play-button-itunes-patch#37]
I've never used this application or patch before. 

I installed and ran it for the first time and when I launch it says rcd is unpatched.  When I press patch, I'm prompted to enter my password the first time.  When I enter my password and hit OK the app immediately dies. 

When I relaunch the app rcd is still unpatched.  I have attempted rebooting and rerunning but get the same result everytime. 

Note I do have both Xcode 7.3 and 8.1 installed.  

I have SIP disabled because I also use TotalFinder which also requres this. 

You've asked for a log.  I don't know where the app's log files are store (might be useful if this was included in the messaging) so I've just included the log from my console.  HTH.

[Console.log.txt](https://github.com/thebitguru/play-button-itunes-patch/files/597443/Console.log.txt)

**Comment by OliverPearmain** [comment]
Aha, found it :-)

[com.thebitguru.Play-Button-iTunes-Patch 2016-11-17 13-07.log.txt](https://github.com/thebitguru/play-button-itunes-patch/files/597448/com.thebitguru.Play-Button-iTunes-Patch.2016-11-17.13-07.log.txt)

**Comment by thebitguru** [comment]
This is odd.  It should be able to write with SIP disabled.  I am guessing that this is still likely a permission issue.  Can you share the output of the following command?

`ls -la /System/Library/CoreServices/rcd.app/Contents/MacOS/`

**Comment by OliverPearmain** [comment]
Sure, the output is...

```
total 48
drwxr-xr-x  3 root  wheel    102 18 Jun 08:52 .
drwxr-xr-x  7 root  wheel    238 18 Jun 08:52 ..
-rwxr-xr-x  1 root  wheel  74272  5 May  2016 rcd
```

**Comment by OliverPearmain** [comment]
FYI, here's my SIP status...

```
$  csrutil status
System Integrity Protection status: enabled (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: enabled
	Filesystem Protections: enabled
	Debugging Restrictions: disabled
	DTrace Restrictions: enabled
	NVRAM Protections: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.
```

**Comment by thebitguru** [comment]
Hmm... maybe that's it.  I am not sure what "custom configuration" means in this case.  Do you want to try disabling it completely?  You can switch it back to your custom configuration afterward.

**Comment by 5ilverorange** [comment]
I experience the same. When I did a check on SIP, I also got the "custom configuration" message, except for mine is a bit different:

Configuration:
	Apple Internal: disabled
	Kext Signing: disabled
	Filesystem Protections: enabled
	Debugging Restrictions: enabled
	DTrace Restrictions: enabled
	NVRAM Protections: enabled
	BaseSystem Verification: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.

**Comment by thebitguru** [comment]
@5ilverorange, from your output, it's the "Filesystem Protections" that's the issue.  Having this enabled doesn't allow the utility to write the new patched file.

**Comment by OliverPearmain** [comment]
I have resolved my issue.  I just needed to disable specifically the `Filesystem Protections` part of SIP. 

In case it helps others, I achieved this by booting into recovery (by holding CMD-R during bootup).  Launcing the Terminal (via the menu) and entering the following command:

`csrutil enable --without filesystem`

Thanks for your help.

**Comment by thebitguru** [comment]
Good to hear.  Thanks for sharing your solution.
