### ISSUE TITLE
Patched but bluetooth button still triggering itunes

### ISSUE THREAD

**Issue by Kevlordofcode** [thebitguru/play-button-itunes-patch#39]
Hi,

I have been using your patch with success since more than one year, thank you for that. However, since the last major OSX update I can't make it work properly again. I am running Sierra version 10.12.2 (16C67) and iTunes version 12.5.4.42, I have followed the usual procedure, installed xcode command line tools, disabled SIP, checked its status, successfully applied the patch, enabled SIP again with all the required reboots and the result is that:
- The play/pause keyboard key does not launch itunes any longer, which is good
- The play/pause button of my bluetooth headset still triggers itunes, which is obviously not good

I have checked everything, the GUI shows rcd as patched, I have tried several backup restore, reboot, repatch (this is why the below attached log is a bit long) and nothing helped.

Do you have an idea of what is causing this issue?

[com.thebitguru.Play-Button-iTunes-Patch 2017-01-05 14-44.docx](https://github.com/thebitguru/play-button-itunes-patch/files/693339/com.thebitguru.Play-Button-iTunes-Patch.2017-01-05.14-44.docx)

**Comment by ErikRye** [comment]
If you didn't do it before, run this command in terminal after SIP is enabled again:  
xcode-select --install

I'm on 10.12.3 and the patch prevents my itunes library from playing automatically like it did before, but itunes does still open...

**Comment by Kevlordofcode** [comment]
Thank you for your advice. Unfortunately it did not solve the issue. I am also on osx 10.12.3 now, it did not change anything either

**Comment by thebitguru** [comment]
Sorry, I overlooked this issue.  @Kevlordofcode, unfortunately, the patch is not expected to prevent this behavior of the bluetooth headsets.  BTW, did your headset come with it's own utility/drivers?

**Comment by Kevlordofcode** [comment]
Hi, I don’t think so. It is a Parrot Zik 2.0 headset and I don’t remember having installed any driver.

Thank you for your answer anyway!

Best regards
