### ISSUE TITLE
How to restore manually if backup doesn't exist?

### ISSUE THREAD

**Issue by garyking** [thebitguru/play-button-itunes-patch#42]
Hello, for some reason, I don't have a backup version of the `rcd` file. I might have had it originally, but it disappeared, perhaps after upgrading to High Sierra?

Anyway, is it possible to restore the original file somehow if I don't have the backup?

**Comment by thebitguru** [comment]
Hi, Gary, 

Does the utility show it as patched?

**Comment by garyking** [comment]
@thebitguru Yes, it shows as "Patched".

**Comment by thebitguru** [comment]
I see.  I had to install High Sierra from scratch because of other issues, but I am surprised that the installer didn't overwrite this file like the previous installers have always done.

Do you have access to another Mac?  Getting the file from there might be the easiest.

Also, are you having any issues with the patched version?

**Comment by garyking** [comment]
If I have access to another Mac, where do I get the file from? I have access to another, older Mac, that's running Sierra rather than High Sierra.

Since installing High Sierra, for some reason, my keyboard media keys would sometimes randomly stop working, and I have to restart my computer to fix them, so I wanted to reset the iTunes Patch to see if that helped.

**Comment by thebitguru** [comment]
It [lives in `/System/Library/CoreServices/rcd.app/Contents/MacOS/`](https://github.com/thebitguru/play-button-itunes-patch/blob/master/iTunes%20Play%20Button%20Patch/Patcher.h#L13).  Using the one from Sierra will likely work if High Sierra installer didn't touch this file, but I would suggest backing up the patched file just in case if that doesn't work.
