### ISSUE TITLE
object file format unrecognized, invalid, or unsuitable

### ISSUE THREAD

**Issue by thebitguru** [thebitguru/play-button-itunes-patch#6]
@bluestarstudios, moving our conversation from #1 here.

> I also get the crashing of RCD. Running OSX 10.8.5. Here's an interesting thing I noticed while running v0.8.3 of the patch:
> 
> ```
> Patching...
>  + Killed any running processes.
>  + Backed up the existing file as rcd_backup_0.8.3_201404141421.33
>  + Patching...
>     Successfully patched the file (found 1 instances at 28702).
>  + Regenerating the code signature...
> /System/Library/CoreServices/rcd.app/Contents/MacOS/rcd: replacing existing signature
> /System/Library/CoreServices/rcd.app/Contents/MacOS/rcd: object file format unrecognized, invalid, or unsuitable
>  + Successfully patched the existing file.
> ```
> Thoughts?
> 

Can you please send me the output of the following command? (note the star at the end).

`md5 /System/Library/CoreServices/rcd.app/Contents/MacOS/rcd*`

**Comment by thebitguru** [comment]
I just published a GUI version of the app that has much better detection and logging.  Can you please try that?  You can download it from http://www.thebitguru.com/projects/iTunesPatch.  If you continue to have problems please paste the content of the log file (accessible through the report issue button) in this issue.  Thanks!

**Comment by bluestarstudios** [comment]
Great job on this! I tested and it works. However it doesn't work when pressing "Play/Pause" on a bluetooth speaker. That still launches iTunes.

**Comment by thebitguru** [comment]
Hmm... what type of speakers do you have?  I am guessing that it might have it's own driver or code that's launching iTunes.

**Comment by bluestarstudios** [comment]
It’s actually the BTS-06. It’s a standard bluetooth speaker. No installation or configuration needed.

**Comment by thebitguru** [comment]
hi @bluestarstudios, sorry, unfortunately, I likely won't get much time to work on the bluetooth related functionality.

I have created #29 to track this and I am looking for someone who can take on this work.  Thanks!
