### ISSUE TITLE
Partially works on 10.9.2

### ISSUE THREAD

**Issue by rjacoby** [thebitguru/play-button-itunes-patch#7]
I have a Monoprice BT headset, which is partially working with this patch.

If I'm running Spotify and pause a track with the headset play/pause button, Spotify pauses and that's fine. When I press again, Spotify unpauses but iTunes also launches!

The headset in question is:
http://www.monoprice.com/Product?c_id=108&cp_id=10823&cs_id=1082708&p_id=9387&seq=1&format=2

Script output:
https://gist.github.com/rjacoby/43fc436a32f07cb88479

**Comment by jmunkki** [comment]
I'm using a Sony SBH-20 (inexpensive and quite useful) - mostly with my iPhone, but also on the MacBook Pro running Mavericks. My issue is that when I disconnect from the adapter, iTunes is launched. Running this patch seemed like it might fix the issue, but iTunes was still getting launched even after a reboot. My guess is that when you disconnect, it sends a "stop" and if you don't have iTunes playing, rcd will launch it. Fortunately it never starts playing, but on some Bluetooth speakers, iTunes will start playing when you disconnect and it can apparently even start playing unwatched rented movies if that's the next thing on the playlist. Not a serious issue for me, but as you can see, some users are really eager to find a solution.

Thanks for your efforts on this. I was really hoping for a "defaults write" type of solution. Apparently this behavior was at some point linked to CD/DVD-autoplay in iTunes and it was possible to disable it by disabling iTunes launching from the CD/DVD settings panel. That panel no longer exists in Mavericks & Yosemite.

**Comment by thebitguru** [comment]
Sorry, unfortunately, I likely won't get much time to work on the bluetooth related functionality.  I have created #29 to track this in a single issue.  I am looking for someone who can take on this work.  Thanks!
